### ISSUE TITLE
Xbox One session shutdown & new session failing often

### ISSUE THREAD

**Issue by joeyparrish** [shaka-project/generic-webdriver-server#44]
Shutdown frequently fails with:

```
15:29:54.787 INFO [ResultConfig.handle] - Executing: [delete session: 51487242-4db9-4e7f-b3e1-d6ddd1d94676])
DELETE /session/c03e4bac1a19dcf1a769cb6371bfe1f1 {}
Session ID c03e4bac1a19dcf1a769cb6371bfe1f1 released
Uninstalling app
15:30:29.094 INFO [ActiveSessions$1.onStop] - Removing session org.openqa.selenium.remote.server.InMemorySession@646227ce
DELETE /session/c03e4bac1a19dcf1a769cb6371bfe1f1 {}
GET /shutdown {}
15:30:38.655 INFO [OsProcess.destroy] - Unable to drain process streams. Ignoring but the exception being swallowed follows.
org.apache.commons.exec.ExecuteException: The stop timeout of 2000 ms was exceeded (Exit value: -559038737)
        at org.apache.commons.exec.PumpStreamHandler.stopThread(PumpStreamHandler.java:295)
[snip]
15:30:38.655 ERROR [OsProcess.destroy] - Unable to kill process java.lang.ProcessImpl@5eb2d927
Done
15:30:38.796 INFO [ResultConfig.handle] - Done: [delete session: 51487242-4db9-4e7f-b3e1-d6ddd1d94676]
```

It seems significant to me that it tries to shut down the session twice.  Perhaps the first call takes too long, and it tries again.

Some of the time, after this happens, if we quickly try to start a new session, this will fail with:
```
https://hostname/api/taskmanager/app?appid=LONG_APP_ID => HTTP 400: {"ErrorMess
age":"Failed to launch the application.","ErrorCode":-2147024894}
    at IncomingMessage.<anonymous> (path\to\npm\node_modules\xbox-one-webdriver-server\xbox-one-utils.js:287:25)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1220:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  method: 'POST',
  url: 'https://hostname/api/taskmanager/app?appid=LONG_APP_ID',
  statusCode: 400,
  body: '{"ErrorMessage":"Failed to launch the application.","ErrorCode":-2147024894}'
}
```

I assume this is because the old session is still being shut down.  In testing with the CLI, I found that building and installing the app to start a new session often takes ~25 seconds.  Then shutting down and uninstalling the app could take as much as ~36 seconds.

**Comment by joeyparrish** [comment]
The `shutdown()` method of the base class will first try to close any open session.  Since closing the session is so slow, Selenium seems to give up waiting and try to shut down.  But the `uninstallApp()` call is still awaiting a result, so it tries to close the session again.

We may be able to fix coordination between close and shutdown for this special case where closing a session is so painfully slow.  Not sure if this should be handled entirely in the Xbox server, or if changes to the base classes would be preferable.

**Comment by joeyparrish** [comment]
The logs about `The stop timeout of 2000 ms was exceeded` may be unavoidable, but may also be safe to ignore if starting and stopping the app can be made more reliable.
